spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio_tracker
    username: root  # your MySQL username
    password: sham@0102  # your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
